---

# Commonly adjusted application variables -
# everything we expect the user to consider changing.
# To avoid clutter, put less-common variables in 'vars/main.yaml'

# Set to 'absent' to undeploy
dt_state: present

# The namespace to create for application deployment.
dt_namespace: mini-apps-data-tier

# Details of the application container image
dt_image_registry: registry.gitlab.com
dt_image_name: informaticsmatters/mini-apps-data-tier/data-tier
dt_image_tag: latest

dt_database_image_registry: docker.io
dt_database_image_name: informaticsmatters/rdkit-cartridge-debian
dt_database_image_tag: Release_2020_03_4

# The ingress hostname and path (http/https assumed)
dt_hostname: squonk.it
dt_hostname_path: data
# The ingress "let's Encrypt" certificate issuer.
# One of 'production' or 'staging'
dt_cert_issuer: production

# The maximum file upload size, '0' implies unlimited.
# Part of the nginx ingress.
dt_ingress_proxy_body_size: 100m

# The pull-secret
dt_pull_secret: SetMe

# The data volume storage class and size (Gi).
# Unless changed ' ' implies the default storage class
dt_data_volume_storageclass: ' '
dt_data_volume_size_g: 10

# Database configuration
dt_database_volume_storageclass: ' '
dt_database_volume_size_g: 5
dt_database_user_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"
dt_database_data_tier_user_password: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters') }}"
