---

# Commonly adjusted application variables -
# everything we expect the user to consider changing.
# To avoid clutter, put less-common variables in 'vars/main.yaml'

# Set to 'absent' to undeploy
dt_state: present

# The namespace to create for application deployment.
dt_namespace: mini-apps-data-tier

# Details of the application container image
dt_image_registry: registry.gitlab.com
dt_image_name: informaticsmatters/mini-apps-data-tier
dt_image_tag: latest

# The ingress hostname (http/https assumed)
dt_hostname: data.informaticsmatters.org
# The ingress "let's Encrypt" certificate issuer.
# One of 'production' or 'staging'
dt_cert_issuer: production

# The pull-secret
dt_pull_secret: SetMe
