---

# Less common application variables -
# Things the user is less-like to want to change (but can).
# This is here to avoid clutter in 'defaults/main.yaml'

# The application Pod Security Policy (PSP)
dt_sa_psp: im-core-unrestricted

# Celery message-broker image
dt_mb_image: rabbitmq:3.6.16-alpine

# Application CPU and Memory requests and limits.
# Requests are required but limits are not.
# Set limit to blank ('') to avoid a limit.
dt_cpu_request: 100m
dt_cpu_limit: 1
dt_mem_request: 500Mi
dt_mem_limit: 0

dt_w_cpu_request: 100m
dt_w_cpu_limit: 1
dt_w_mem_request: 500Mi
dt_w_mem_limit: 0

dt_mb_cpu_request: 100m
dt_mb_cpu_limit: 500m
dt_mb_mem_request: 128Mi
dt_mb_mem_limit: 0

dt_database_cpu_request: 100m
dt_database_cpu_limit: 500m
dt_database_mem_request: 250Mi
dt_database_mem_limit: 1Gi

# The role users are expected to have in order to use the data-tier.
# This is a role, expected in the Keycloak realm for mini-app users.
dt_required_role: standard-user

# Sentry DSN.
# Set to enable integration with the Sentry SDK.
dt_sentry_dsn: ''

# General variables

wait_timeout: 120
bind_timeout: 0
pod_ready_timeout: 600
