---

# Less common application variables -
# Things the user is less-like to want to change (but can).
# This is here to avoid clutter in 'defaults/main.yaml'

# The application Pod Security Policy (PSP)
dt_sa_psp: im-core-unrestricted

# Application CPU and Memory requests and limits.
# Requests are required but limits are not.
# Set limit to blank ('') to avoid a limit.
dt_cpu_request: 250m
dt_cpu_limit: 500m
dt_mem_request: 250Mi
dt_mem_limit: 250Mi

dt_database_cpu_request: 100m
dt_database_cpu_limit: 500m
dt_database_mem_request: 250Mi
dt_database_mem_limit: 1Gi

# The role users are expected to have in order to use the data-tier.
# This is a role, expected in the Keycloak realm for mini-app users.
dt_required_role: standard-user

# General variables

wait_timeout: 120
bind_timeout: 0
pod_ready_timeout: 600
