---

# Assert key variables
- name: Assert key variables
  assert:
    that:
    - dt_pull_secret|string|length > 0
    - dt_pull_secret|string != 'SetMe'

# Create the namespace and other basic materials

- name: Create namespace ({{ dt_namespace }})
  k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes

- name: Create DockerHub image pull secret
  k8s:
    definition: "{{ lookup('template', 'secret-dh-imagepull.yaml.j2') }}"
    wait: yes
  vars:
    pull_namespace: "{{ dt_namespace }}"
    pull_secret: "{{ dt_dockerhub_pullsecret }}"
  when: dt_dockerhub_pullsecret|string|length > 0

- name: Create namespace material
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - serviceaccount
  - role
  - role-pod-runner
  - rolebinding-role-sa
  - rolebinding-role-pod-runner-sa

- name: Relax ({{ dt_namespace }} 'default' service account (for cert-manager)
  k8s:
    definition: "{{ lookup('template', 'rolebinding-default-sa.yaml.j2') }}"
    wait: yes

# Defer next actions to database and data-tier logic...

- include_tasks: deploy-database.yaml
- include_tasks: deploy-data-manager-api.yaml
